Repository Workiva/w_transport, pull requests merged in 2023-08, with the labels that each got.

#400 Make as much of the public API non-nullable as possible
  _test_server/lib/servers.dart
  _test_server/lib/src/handlers/example/http/cross_origin_credentials_handlers.dart
  _test_server/lib/src/handlers/example/http/cross_origin_file_transfer_handlers.dart
  _test_server/lib/src/handlers/example/http/proxy_cross_origin_file_transfer_handlers.dart
  _test_server/lib/src/handlers/example/ws/routes.dart
  _test_server/lib/src/handlers/test/http/custom.dart
  _test_server/lib/src/handlers/test/http/reflect_handler.dart
  _test_server/lib/src/logger.dart
  _test_server/lib/src/router.dart
  example/pubspec.yaml
  lib/src/browser_transport_platform_with_sockjs.dart
  lib/src/http/base_request.dart
  lib/src/http/browser/multipart_request.dart
  lib/src/http/browser/request_mixin.dart
  lib/src/http/common/http_client.dart
  lib/src/http/common/plain_text_request.dart
  lib/src/http/common/request.dart
  lib/src/http/common/streamed_request.dart
  lib/src/http/finalized_request.dart
  lib/src/http/http_body.dart
  lib/src/http/http_client.dart
  lib/src/http/mock/request_mixin.dart
  lib/src/http/mock/requests.dart
  lib/src/http/mock/response.dart
  lib/src/http/multipart_file.dart
  lib/src/http/request_exception.dart
  lib/src/http/request_progress.dart
  lib/src/http/requests.dart
  lib/src/http/response.dart
  lib/src/http/utils.dart
  lib/src/http/vm/request_mixin.dart
  lib/src/mocks/mock_http.dart
  lib/src/mocks/mock_web_socket.dart
  lib/src/mocks/mock_web_socket_server.dart
  lib/src/transport_platform.dart
  lib/src/web_socket/browser/sockjs_wrapper.dart
  lib/src/web_socket/browser/web_socket.dart
  lib/src/web_socket/global_web_socket_monitor.dart
  lib/src/web_socket/mock/w_socket.dart
  lib/src/web_socket/vm/web_socket.dart
  test/integration/http/common_request/browser_test.dart
  test/integration/http/common_request/suite.dart
  test/integration/http/form_request/suite.dart
  test/integration/http/http_static/suite.dart
  test/integration/http/mock_endpoints/upload.dart
  test/integration/platforms/mock_aware_transport_platform_test.dart
  test/integration/platforms/transport_platform_test.dart
  test/unit/http/client_test.dart
  test/unit/http/multipart_file_test.dart
  test/unit/http/multipart_request_test.dart
  test/unit/http/plain_text_request_test.dart
  test/unit/http/request_exception_test.dart
  test/unit/http/request_test.dart
  test/unit/http/response_test.dart
  test/unit/http/streamed_request_test.dart
  test/unit/http/utils_test.dart
  test/unit/mocks/mock_response_test.dart
  test/unit/mocks/mock_web_socket_test.dart
Labels: Security Review Required

#402 Update changelog
  CHANGELOG.md
Labels: RM Ready

#403 RM-190883 Release w_transport 5.0.0
  pubspec.yaml
Labels: RM Ready

#404 Nullable fixes
  CHANGELOG.md
  lib/src/http/request_exception.dart
  pubspec.yaml
  test/unit/http/request_test.dart
Labels: semver: Patch, RM Ready

#406 RM-208795 Release w_transport 5.0.1
  pubspec.yaml
Labels: semver: Patch, RM Ready

#390 FEA-2422: Allow setting a default timeout for all requests
  lib/src/http/base_request.dart
  lib/src/http/client.dart
  lib/src/http/common/http_client.dart
  lib/src/http/common/request.dart
  lib/w_transport.dart
  test/integration/http/common_request/suite.dart
Labels: semver: Minor, RM Ready

#408 Add changelog entry for 5.1.0
  CHANGELOG.md
Labels: RM Ready

#410 RM-208849 Release w_transport 5.1.0
  pubspec.yaml
Labels: RM Ready
